name: Fork Updater

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
   - cron: 0 13 * * 1

jobs:
  spring-boot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: maly7/spring-boot
        token:  ${{ secrets.TOKEN }}
    - run: |
        git remote add upstream https://github.com/spring-projects/spring-boot.git
        git fetch upstream
        git merge upstream/main
        git push
  spring-hateoas:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: maly7/spring-hateoas
        token:  ${{ secrets.TOKEN }}
    - run: |
        git remote add upstream https://github.com/spring-projects/spring-hateoas.git
        git fetch upstream
        git merge upstream/main
        git push
  spring-cloud-zookeeper:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: maly7/spring-cloud-zookeeper
        token:  ${{ secrets.TOKEN }}
    - run: |
        git remote add upstream https://github.com/spring-cloud/spring-cloud-zookeeper.git
        git fetch upstream
        git merge upstream/main
        git push
  spring-cloud-openfeign:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: maly7/spring-cloud-openfeign
        token:  ${{ secrets.TOKEN }}
    - run: |
        git remote add upstream https://github.com/spring-cloud/spring-cloud-openfeign.git
        git fetch upstream
        git merge upstream/main
        git push
  spring-cloud-gateway:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: maly7/spring-cloud-gateway
        token:  ${{ secrets.TOKEN }}
    - run: |
        git remote add upstream https://github.com/spring-cloud/spring-cloud-gateway.git
        git fetch upstream
        git merge upstream/main
        git push
  spring-cloud-consul:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: maly7/spring-cloud-consul
        token:  ${{ secrets.TOKEN }}
    - run: |
        git remote add upstream https://github.com/spring-cloud/spring-cloud-consul.git
        git fetch upstream
        git merge upstream/main
        git push
  feign:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: maly7/feign
        token:  ${{ secrets.TOKEN }}
    - run: |
        git remote add upstream https://github.com/OpenFeign/feign.git
        git fetch upstream
        git merge upstream/master
        git push
  exercism-java:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: maly7/java
        token:  ${{ secrets.TOKEN }}
    - run: |
        git remote add upstream https://github.com/exercism/java.git
        git fetch upstream
        git merge upstream/main
        git push
  parrit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: maly7/Parrit
        token:  ${{ secrets.TOKEN }}
    - run: |
        git remote add upstream https://github.com/Parrit/Parrit.git
        git fetch upstream
        git merge upstream/master
        git push
