name: Fork Updater

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
   - cron: 0 13 * * 1

jobs:
  spring-boot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: maly7/spring-boot
        token:  ${{ secrets.TOKEN }}
    - run: |
        git remote add upstream https://github.com/spring-projects/spring-boot.git
        git fetch upstream
